// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"
#include "screens/ui_Screen3.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_878964720);    // assets/icon_temp_32-removebg-preview.png
LV_IMG_DECLARE(ui_img_icon_humid_png);    // assets/icon_humid.png
LV_IMG_DECLARE(ui_img_icon_home_40_png);    // assets/icon_home_40.png
LV_IMG_DECLARE(ui_img_icon_ngoai_troi_40_png);    // assets/Icon_ngoai_troi_40.png
LV_IMG_DECLARE(ui_img_icon_aqi_32_png);    // assets/icon_aqi_32.png

// FONTS
LV_FONT_DECLARE(ui_font_FontVN);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
