// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_event_slider_brightness(lv_event_t * e);
void action_save_time_to_rtc(lv_event_t * e);
void change_unit_action(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
