// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_Panel9 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_Label14 = NULL;
// event funtions
void ui_event_Screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Screen1, LV_SCREEN_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_Screen1_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Screen3, LV_SCREEN_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_Screen3_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel8, 460);
    lv_obj_set_height(ui_Panel8, 270);
    lv_obj_set_x(ui_Panel8, 0);
    lv_obj_set_y(ui_Panel8, 18);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel8, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Panel8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_Panel8);
    lv_obj_set_height(ui_Panel9, 70);
    lv_obj_set_width(ui_Panel9, lv_pct(100));
    lv_obj_set_x(ui_Panel9, -452);
    lv_obj_set_y(ui_Panel9, 299);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel9, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0xA7A7A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_Label15, 380);
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 15);
    lv_obj_set_y(ui_Label15, 0);
    lv_obj_set_align(ui_Label15, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_Label15, LV_LABEL_LONG_MODE_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Label15,
                      "Bản tin chiều: Hoàn thành thiết lập UI/UX cho hệ thống nhúng với SquareLine...");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0x0F0C0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &ui_font_FontVN, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Panel8);
    lv_obj_set_height(ui_Panel1, 70);
    lv_obj_set_width(ui_Panel1, lv_pct(100));
    lv_obj_set_x(ui_Panel1, -452);
    lv_obj_set_y(ui_Panel1, 299);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xA7A7A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label1, 380);
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 15);
    lv_obj_set_y(ui_Label1, 0);
    lv_obj_set_align(ui_Label1, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_Label1, LV_LABEL_LONG_MODE_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Label1,
                      "Bản tin chiều: Hoàn thành thiết lập UI/UX cho hệ thống nhúng với SquareLine...");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x0F0C0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_FontVN, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Panel8);
    lv_obj_set_height(ui_Panel2, 70);
    lv_obj_set_width(ui_Panel2, lv_pct(100));
    lv_obj_set_x(ui_Panel2, -452);
    lv_obj_set_y(ui_Panel2, 299);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xA7A7A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label16, 380);
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 15);
    lv_obj_set_y(ui_Label16, 0);
    lv_obj_set_align(ui_Label16, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_Label16, LV_LABEL_LONG_MODE_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Label16,
                      "Bản tin chiều: Hoàn thành thiết lập UI/UX cho hệ thống nhúng với SquareLine...");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x0F0C0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &ui_font_FontVN, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 6);
    lv_obj_set_y(ui_Label14, -135);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "HOT NEWS");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0x070303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Panel8 = NULL;
    ui_Panel9 = NULL;
    ui_Label15 = NULL;
    ui_Panel1 = NULL;
    ui_Label1 = NULL;
    ui_Panel2 = NULL;
    ui_Label16 = NULL;
    ui_Label14 = NULL;

}
