// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern void ui_event_Slider4(lv_event_t * e);
extern lv_obj_t * ui_Slider4;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_RollerHour;
extern lv_obj_t * ui_RollerMin;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_RollerDate;
extern lv_obj_t * ui_RollerMonth;
extern lv_obj_t * ui_RollerYear;
extern lv_obj_t * ui_Label13;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label3;
extern void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

