// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_LabelTime = NULL;
lv_obj_t * ui_LabelDate = NULL;
lv_obj_t * ui_Image19 = NULL;
lv_obj_t * ui_LabelHomeTemp = NULL;
lv_obj_t * ui_Image20 = NULL;
lv_obj_t * ui_LabelHomeHum = NULL;
lv_obj_t * ui_Image21 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Image23 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_LabelOutTemp = NULL;
lv_obj_t * ui_LabelOutHum = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_LabelAQI = NULL;
// event funtions
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Screen2, LV_SCREEN_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTime = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelTime, LV_SIZE_CONTENT);   /// 157
    lv_obj_set_height(ui_LabelTime, LV_SIZE_CONTENT);    /// 126
    lv_obj_set_x(ui_LabelTime, -2);
    lv_obj_set_y(ui_LabelTime, -128);
    lv_obj_set_align(ui_LabelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTime, "10:37");
    lv_obj_set_style_text_color(ui_LabelTime, lv_color_hex(0x0F0404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTime, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDate = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDate, -1);
    lv_obj_set_y(ui_LabelDate, -95);
    lv_obj_set_align(ui_LabelDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDate, "Thứ 3, ngày 18 tháng 8 năm 2026");
    lv_obj_set_style_text_color(ui_LabelDate, lv_color_hex(0x0F0404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDate, &ui_font_FontVN, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image19 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image19, &ui_img_878964720);
    lv_obj_set_width(ui_Image19, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image19, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image19, -176);
    lv_obj_set_y(ui_Image19, 38);
    lv_obj_set_align(ui_Image19, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelHomeTemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelHomeTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHomeTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHomeTemp, -140);
    lv_obj_set_y(ui_LabelHomeTemp, 39);
    lv_obj_set_align(ui_LabelHomeTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHomeTemp, "32 C");
    lv_obj_set_style_text_color(ui_LabelHomeTemp, lv_color_hex(0x0C0909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHomeTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image20 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image20, &ui_img_icon_humid_png);
    lv_obj_set_width(ui_Image20, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image20, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image20, -176);
    lv_obj_set_y(ui_Image20, 83);
    lv_obj_set_align(ui_Image20, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelHomeHum = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelHomeHum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHomeHum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHomeHum, -139);
    lv_obj_set_y(ui_LabelHomeHum, 84);
    lv_obj_set_align(ui_LabelHomeHum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHomeHum, "50 %");
    lv_obj_set_style_text_color(ui_LabelHomeHum, lv_color_hex(0x110808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHomeHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image21 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image21, &ui_img_icon_home_40_png);
    lv_obj_set_width(ui_Image21, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_Image21, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_Image21, -145);
    lv_obj_set_y(ui_Image21, -40);
    lv_obj_set_align(ui_Image21, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -147);
    lv_obj_set_y(ui_Label7, 2);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Trong nhà");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x0F0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_FontVN, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 106);
    lv_obj_set_y(ui_Label2, 0);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Hà Nội");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x0F0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_FontVN, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image23 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image23, &ui_img_icon_ngoai_troi_40_png);
    lv_obj_set_width(ui_Image23, LV_SIZE_CONTENT);   /// 29
    lv_obj_set_height(ui_Image23, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_Image23, 108);
    lv_obj_set_y(ui_Image23, -37);
    lv_obj_set_align(ui_Image23, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image1, &ui_img_878964720);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image1, 88);
    lv_obj_set_y(ui_Image1, 36);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image2, &ui_img_icon_humid_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image2, 88);
    lv_obj_set_y(ui_Image2, 85);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelOutTemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelOutTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOutTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOutTemp, 123);
    lv_obj_set_y(ui_LabelOutTemp, 37);
    lv_obj_set_align(ui_LabelOutTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelOutTemp, "32 C");
    lv_obj_set_style_text_color(ui_LabelOutTemp, lv_color_hex(0x0C0909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelOutTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelOutHum = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelOutHum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOutHum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOutHum, 122);
    lv_obj_set_y(ui_LabelOutHum, 86);
    lv_obj_set_align(ui_LabelOutHum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelOutHum, "50 %");
    lv_obj_set_style_text_color(ui_LabelOutHum, lv_color_hex(0x110808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelOutHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image3, &ui_img_icon_aqi_32_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_Image3, 85);
    lv_obj_set_y(ui_Image3, 132);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelAQI = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelAQI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAQI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAQI, 115);
    lv_obj_set_y(ui_LabelAQI, 129);
    lv_obj_set_align(ui_LabelAQI, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAQI, "50");
    lv_obj_set_style_text_color(ui_LabelAQI, lv_color_hex(0x110808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAQI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAQI, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_LabelTime = NULL;
    ui_LabelDate = NULL;
    ui_Image19 = NULL;
    ui_LabelHomeTemp = NULL;
    ui_Image20 = NULL;
    ui_LabelHomeHum = NULL;
    ui_Image21 = NULL;
    ui_Label7 = NULL;
    ui_Label2 = NULL;
    ui_Image23 = NULL;
    ui_Image1 = NULL;
    ui_Image2 = NULL;
    ui_LabelOutTemp = NULL;
    ui_LabelOutHum = NULL;
    ui_Image3 = NULL;
    ui_LabelAQI = NULL;

}
