// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_LabelTime;
extern lv_obj_t * ui_LabelDate;
extern lv_obj_t * ui_Image19;
extern lv_obj_t * ui_LabelHomeTemp;
extern lv_obj_t * ui_Image20;
extern lv_obj_t * ui_LabelHomeHum;
extern lv_obj_t * ui_Image21;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Image23;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_LabelOutTemp;
extern lv_obj_t * ui_LabelOutHum;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_LabelAQI;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

