// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Slider4 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_RollerHour = NULL;
lv_obj_t * ui_RollerMin = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_RollerDate = NULL;
lv_obj_t * ui_RollerMonth = NULL;
lv_obj_t * ui_RollerYear = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Switch1 = NULL;
// event funtions
void ui_event_Screen3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Screen2, LV_SCREEN_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Slider4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_event_slider_brightness(e);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        action_save_time_to_rtc(e);
    }
}

void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        change_unit_action(e);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -145);
    lv_obj_set_y(ui_Label8, -67);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Độ sáng");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x120A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &ui_font_FontVN, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 4);
    lv_obj_set_y(ui_Label9, -130);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "SETTINGS");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x0A0303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider4 = lv_slider_create(ui_Screen3);
    lv_slider_set_value(ui_Slider4, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider4) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_Slider4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider4, 269);
    lv_obj_set_height(ui_Slider4, 20);
    lv_obj_set_x(ui_Slider4, 56);
    lv_obj_set_y(ui_Slider4, -67);
    lv_obj_set_align(ui_Slider4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Slider4, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider4, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider4,
                                                                                              lv_obj_get_style_pad_right(ui_Slider4, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Label10 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -148);
    lv_obj_set_y(ui_Label10, -18);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Thời gian");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x120A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &ui_font_FontVN, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerHour = lv_roller_create(ui_Screen3);
    lv_roller_set_options(ui_RollerHour,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_RollerHour, 78);
    lv_obj_set_height(ui_RollerHour, 47);
    lv_obj_set_x(ui_RollerHour, -43);
    lv_obj_set_y(ui_RollerHour, -18);
    lv_obj_set_align(ui_RollerHour, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_RollerHour, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerHour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerMin = lv_roller_create(ui_Screen3);
    lv_roller_set_options(ui_RollerMin,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_RollerMin, 78);
    lv_obj_set_height(ui_RollerMin, 47);
    lv_obj_set_x(ui_RollerMin, 56);
    lv_obj_set_y(ui_RollerMin, -18);
    lv_obj_set_align(ui_RollerMin, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_RollerMin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerMin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 5);
    lv_obj_set_y(ui_Label11, -22);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, ":");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x100606), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &ui_font_FontVN, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -152);
    lv_obj_set_y(ui_Label12, 35);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Ngày tháng năm");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x120A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &ui_font_FontVN, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerDate = lv_roller_create(ui_Screen3);
    lv_roller_set_options(ui_RollerDate,
                          "01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_RollerDate, 79);
    lv_obj_set_height(ui_RollerDate, 47);
    lv_obj_set_x(ui_RollerDate, -43);
    lv_obj_set_y(ui_RollerDate, 35);
    lv_obj_set_align(ui_RollerDate, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_RollerDate, &ui_font_FontVN, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollerDate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerMonth = lv_roller_create(ui_Screen3);
    lv_roller_set_options(ui_RollerMonth, "01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_RollerMonth, 79);
    lv_obj_set_height(ui_RollerMonth, 47);
    lv_obj_set_x(ui_RollerMonth, 55);
    lv_obj_set_y(ui_RollerMonth, 36);
    lv_obj_set_align(ui_RollerMonth, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_RollerMonth, &ui_font_FontVN, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollerMonth, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerMonth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerYear = lv_roller_create(ui_Screen3);
    lv_roller_set_options(ui_RollerYear,
                          "2026\n2027\n2028\n2029\n2030\n2031\n2032\n2033\n2034\n2035\n2036\n2037\n2038\n2039\n2040", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_RollerYear, 79);
    lv_obj_set_height(ui_RollerYear, 47);
    lv_obj_set_x(ui_RollerYear, 153);
    lv_obj_set_y(ui_RollerYear, 36);
    lv_obj_set_align(ui_RollerYear, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_RollerYear, &ui_font_FontVN, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollerYear, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerYear, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -149);
    lv_obj_set_y(ui_Label13, 96);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Đơn vị (F)");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x120A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_FontVN, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_button_create(ui_Screen3);
    lv_obj_set_width(ui_Button1, 61);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, 198);
    lv_obj_set_y(ui_Button1, -126);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button1, &ui_font_FontVN, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 199);
    lv_obj_set_y(ui_Label3, -127);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Lưu");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_FontVN, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_Screen3);
    lv_obj_set_width(ui_Switch1, 68);
    lv_obj_set_height(ui_Switch1, 32);
    lv_obj_set_x(ui_Switch1, -46);
    lv_obj_set_y(ui_Switch1, 98);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Slider4, ui_event_Slider4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Label8 = NULL;
    ui_Label9 = NULL;
    ui_Slider4 = NULL;
    ui_Label10 = NULL;
    ui_RollerHour = NULL;
    ui_RollerMin = NULL;
    ui_Label11 = NULL;
    ui_Label12 = NULL;
    ui_RollerDate = NULL;
    ui_RollerMonth = NULL;
    ui_RollerYear = NULL;
    ui_Label13 = NULL;
    ui_Button1 = NULL;
    ui_Label3 = NULL;
    ui_Switch1 = NULL;

}
